Check for r_asm and r_anal in configure.acr

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -218,7 +218,7 @@ case $flag in
 echo "PKGNAME:   r2ghidra"
 echo "VERSION:   5.0.1"
 echo "LANGS:     c++"
-echo "PKG-CONFIG:  r_core"
+echo "PKG-CONFIG:  r_core r_asm r_anal"
 	exit 0
 	;;
 --cache-file)
@@ -281,7 +281,7 @@ parse_options "$1"
 shift
 done
 
-ENVWORDS="MANDIR INFODIR LIBDIR INCLUDEDIR LOCALSTATEDIR SYSCONFDIR DATADIR DOCDIR LIBEXECDIR SBINDIR BINDIR EPREFIX PREFIX SPREFIX TARGET HOST BUILD INSTALL INSTALL_LIB INSTALL_MAN INSTALL_PROGRAM INSTALL_PROGRAM_STRIP INSTALL_DIR INSTALL_SCRIPT INSTALL_DATA HOST_OS HOST_CPU BUILD_OS BUILD_CPU TARGET_OS TARGET_CPU VERSION VERSION_MAJOR VERSION_MINOR VERSION_PATCH VERSION_NUMBER PKGNAME VPATH CONTACT CONTACT_NAME CONTACT_MAIL CXX CXXFLAGS LDFLAGS HAVE_LANG_CXX CPP HAVE_GIT GIT PKGCONFIG R2_CFLAGS R2_LDFLAGS HAVE_PKGCFG_R_CORE HAVE_R2 R2 HAVE_BISON BISON HAVE_FLEX FLEX R2_PREFIX R2_USER_PLUGINS R2_LIBR_PLUGINS"
+ENVWORDS="MANDIR INFODIR LIBDIR INCLUDEDIR LOCALSTATEDIR SYSCONFDIR DATADIR DOCDIR LIBEXECDIR SBINDIR BINDIR EPREFIX PREFIX SPREFIX TARGET HOST BUILD INSTALL INSTALL_LIB INSTALL_MAN INSTALL_PROGRAM INSTALL_PROGRAM_STRIP INSTALL_DIR INSTALL_SCRIPT INSTALL_DATA HOST_OS HOST_CPU BUILD_OS BUILD_CPU TARGET_OS TARGET_CPU VERSION VERSION_MAJOR VERSION_MINOR VERSION_PATCH VERSION_NUMBER PKGNAME VPATH CONTACT CONTACT_NAME CONTACT_MAIL CXX CXXFLAGS LDFLAGS HAVE_LANG_CXX CPP HAVE_GIT GIT PKGCONFIG R2_CFLAGS R2_LDFLAGS HAVE_PKGCFG_R_CORE R2ASM_CFLAGS R2ASM_LDFLAGS HAVE_PKGCFG_R_ASM R2ANAL_CFLAGS R2ANAL_LDFLAGS HAVE_PKGCFG_R_ANAL HAVE_R2 R2 HAVE_BISON BISON HAVE_FLEX FLEX R2_PREFIX R2_USER_PLUGINS R2_LIBR_PLUGINS"
 
 create_environ
 
@@ -394,6 +394,32 @@ tmp=`${PKGCONFIG} --libs r_core 2>/dev/null`
 if [ $? = 0 ]; then
 echo yes; HAVE_PKGCFG_R_CORE=1;
 R2_LDFLAGS=$tmp; fi; fi
+if [ -z "${PKGCONFIG}" ]; then pkg-config --version >/dev/null 2>&1 ; if [ 0 = 0 ]; then PKGCONFIG=pkg-config ; else PKGCONFIG=pkgconf ; fi; fi
+printf 'checking pkg-config flags for r_asm... '
+tmp=`${PKGCONFIG} --cflags r_asm 2>/dev/null`
+if [ $? != 0 ]; then echo no ; HAVE_PKGCFG_R_ASM=0;
+R2ASM_CFLAGS='';R2ASM_LDFLAGS='';
+echo 'This package is required'
+exit 1
+else
+R2ASM_CFLAGS=$tmp;
+tmp=`${PKGCONFIG} --libs r_asm 2>/dev/null`
+if [ $? = 0 ]; then
+echo yes; HAVE_PKGCFG_R_ASM=1;
+R2ASM_LDFLAGS=$tmp; fi; fi
+if [ -z "${PKGCONFIG}" ]; then pkg-config --version >/dev/null 2>&1 ; if [ 0 = 0 ]; then PKGCONFIG=pkg-config ; else PKGCONFIG=pkgconf ; fi; fi
+printf 'checking pkg-config flags for r_anal... '
+tmp=`${PKGCONFIG} --cflags r_anal 2>/dev/null`
+if [ $? != 0 ]; then echo no ; HAVE_PKGCFG_R_ANAL=0;
+R2ANAL_CFLAGS='';R2ANAL_LDFLAGS='';
+echo 'This package is required'
+exit 1
+else
+R2ANAL_CFLAGS=$tmp;
+tmp=`${PKGCONFIG} --libs r_anal 2>/dev/null`
+if [ $? = 0 ]; then
+echo yes; HAVE_PKGCFG_R_ANAL=1;
+R2ANAL_LDFLAGS=$tmp; fi; fi
 ochof "checking for r2... "
 if [ -x "${R2}" ]; then
 	FIND=${R2}
