More build cleanups

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,5 +1,5 @@
 #!/bin/sh
-# This script was automatically generated by ACR v1.9.6
+# This script was automatically generated by ACR v1.9.7
 # @author: pancake <nopcode.org>
 # @url:    http://www.nopcode.org
 # @repo:   git clone https://github.com/radare/acr
@@ -18,15 +18,6 @@ control_c() {
   exit 1
 }
 trap control_c 2
-printf "checking for cpp... "
-if [ "${CROSSBUILD}" = 1 ]; then
-(exec ${HOST}-${CPP} --help >/dev/null 2>&1)
-[ $? = 0 ] && CPP="${HOST}-${CPP}"
-fi
-(echo "int main(int ac, char **av){return 0;}" | ${CPP}  >/dev/null 2>&1)
-if [ $? = 0 ]; then echo ${CPP}; else
-echo "ERROR: ${CPP} cannot parse sources"; fi
-
 split_host() {
 S="$"
 while : ; do
@@ -196,7 +187,7 @@ if [ "$QUIET" = 1 ]; then
 	echo "5.0.0"
 	exit 0
 fi
-echo "r2ghidra-5.0.0 configuration script done with acr v1.9.6.
+echo "r2ghidra-5.0.0 configuration script done with acr v1.9.7.
 The 'Free Software Foundation' message is only for autodetection.
 Originally written by pancake <nopcode.org>."
 exit 0
@@ -290,7 +281,7 @@ parse_options "$1"
 shift
 done
 
-ENVWORDS="MANDIR INFODIR LIBDIR INCLUDEDIR LOCALSTATEDIR SYSCONFDIR DATADIR DOCDIR LIBEXECDIR SBINDIR BINDIR EPREFIX PREFIX SPREFIX TARGET HOST BUILD INSTALL INSTALL_LIB INSTALL_MAN INSTALL_PROGRAM INSTALL_PROGRAM_STRIP INSTALL_DIR INSTALL_SCRIPT INSTALL_DATA HOST_OS HOST_CPU BUILD_OS BUILD_CPU TARGET_OS TARGET_CPU VERSION VERSION_MAJOR VERSION_MINOR VERSION_PATCH VERSION_NUMBER PKGNAME VPATH CONTACT CONTACT_NAME CONTACT_MAIL CXX CXXFLAGS LDFLAGS HAVE_LANG_CXX CPP HAVE_GIT GIT PKGCONFIG R2_CFLAGS R2_LDFLAGS HAVE_PKGCFG_R_CORE HAVE_R2 R2 HAVE_BISON BISON HAVE_flex flex R2_PREFIX R2_USER_PLUGINS R2_LIBR_PLUGINS"
+ENVWORDS="MANDIR INFODIR LIBDIR INCLUDEDIR LOCALSTATEDIR SYSCONFDIR DATADIR DOCDIR LIBEXECDIR SBINDIR BINDIR EPREFIX PREFIX SPREFIX TARGET HOST BUILD INSTALL INSTALL_LIB INSTALL_MAN INSTALL_PROGRAM INSTALL_PROGRAM_STRIP INSTALL_DIR INSTALL_SCRIPT INSTALL_DATA HOST_OS HOST_CPU BUILD_OS BUILD_CPU TARGET_OS TARGET_CPU VERSION VERSION_MAJOR VERSION_MINOR VERSION_PATCH VERSION_NUMBER PKGNAME VPATH CONTACT CONTACT_NAME CONTACT_MAIL CXX CXXFLAGS LDFLAGS HAVE_LANG_CXX CPP HAVE_GIT GIT PKGCONFIG R2_CFLAGS R2_LDFLAGS HAVE_PKGCFG_R_CORE HAVE_R2 R2 HAVE_BISON BISON HAVE_FLEX FLEX R2_PREFIX R2_USER_PLUGINS R2_LIBR_PLUGINS"
 
 create_environ
 
@@ -304,12 +295,12 @@ ocho "checking target system type... ${TARGET}"
 ocho "checking for working directories... ${WODIS}"
 ocho "using prefix '${PREFIX}'"
 ACR_RMFILES=" test.c test.cxx a.out a.exe"
-
+	
 
 
 COMPILER=CXX
 HAVE_LANG_CXX=1
-printf "checking for c++ compiler... "
+ochof "checking for c++ compiler... "
 if [ "${CROSSBUILD}" = 1 ]; then
 (command -v ${HOST}-${CXX} 2>&1 >/dev/null)
 if [ "$?" = 0 ]; then CXX="${HOST}-${CXX}"; fi
@@ -325,6 +316,14 @@ echo "ERROR: ${CXX} cannot create executables" >&2 ;
 do_remove
 exit 1
  fi
+	ochof "checking for cpp... "
+	if [ "${CROSSBUILD}" = 1 ]; then
+	(exec ${HOST}-${CPP} --help >/dev/null 2>&1)
+	[ $? = 0 ] && CPP="${HOST}-${CPP}"
+	fi
+	(echo "int main(int ac, char **av){return 0;}" | ${CPP}  >/dev/null 2>&1)
+	if [ 0 = 0 ]; then echo ${CPP}; else
+	echo "ERROR: ${CPP} cannot parse sources"; fi
 ochof "checking for git... "
 if [ -x "${GIT}" ]; then
 	FIND=${GIT}
@@ -452,8 +451,8 @@ fi
 	echo "error: This program is required." >&2
 	exit 1 ; fi
 ochof "checking for flex... "
-if [ -x "${flex}" ]; then
-	FIND=${flex}
+if [ -x "${FLEX}" ]; then
+	FIND=${FLEX}
 else
 	FIND=""
 	IFS=:
@@ -467,11 +466,11 @@ else
 fi
 if [ -n "${FIND}" ]; then
 	ocho ${FIND};
-HAVE_flex=1
-	flex=${FIND}
+HAVE_FLEX=1
+	FLEX=${FIND}
 else
-	HAVE_flex=0
-	flex=flex
+	HAVE_FLEX=0
+	FLEX=flex
 if [ "" = 1 ]; then
 echo "Cannot find flex" >&2
 else
