Use latest ACR to support EXEC!

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,5 +1,5 @@
 #!/bin/sh
-# This script was automatically generated by ACR v1.9.5
+# This script was automatically generated by ACR v1.9.6
 # @author: pancake <nopcode.org>
 # @url:    http://www.nopcode.org
 # @repo:   git clone https://github.com/radare/acr
@@ -196,7 +196,7 @@ if [ "$QUIET" = 1 ]; then
 	echo "5.0.0-git"
 	exit 0
 fi
-echo "r2ghidra-5.0.0-git configuration script done with acr v1.9.5.
+echo "r2ghidra-5.0.0-git configuration script done with acr v1.9.6.
 The 'Free Software Foundation' message is only for autodetection.
 Originally written by pancake <nopcode.org>."
 exit 0
@@ -480,6 +480,7 @@ if [ $? = 0 ]; then
 else
 	R2_PREFIX=""
 	echo "not found"
+echo 'required'; exit 1
 fi
 printf "checking exec r2 -H R2_USER_PLUGINS... "
 R2_USER_PLUGINS="`r2 -H R2_USER_PLUGINS 2>/dev/null`"
@@ -488,6 +489,7 @@ if [ $? = 0 ]; then
 else
 	R2_USER_PLUGINS=""
 	echo "not found"
+echo 'required'; exit 1
 fi
 printf "checking exec r2 -H R2_LIBR_PLUGINS... "
 R2_LIBR_PLUGINS="`r2 -H R2_LIBR_PLUGINS 2>/dev/null`"
@@ -496,6 +498,7 @@ if [ $? = 0 ]; then
 else
 	R2_LIBR_PLUGINS=""
 	echo "not found"
+echo 'required'; exit 1
 fi
 SEDFLAGS=" -e '"
 COUNT=0
